# POST http://localhost:3000/users/create
# Content-Type: application/json

# {
#   "email": "new6889@example.com",
#   "password": "mypassword",
#   "role": "admin"
# }

# POST http://localhost:3000/auth/login
# Content-Type: application/json

# {
#   "email": "newuser96889@example.com",
#   "password": "mypassword"
# }

# for list all user 

# curl -X GET http://localhost:3000/users/all -H "Content-Type: application/json"


# for create assessment

# curl -X POST http://localhost:3000/assessments \
#      -H "Content-Type: application/json" \
#      -d '{
#            "name": "AI",
#            "parent_id": null
#          }'

# for delete assessemnt

# curl -X DELETE http://localhost:3000/assessments/4

# # for update assessment
# curl -X PUT http://localhost:3000/assessments/3 \
#      -H "Content-Type: application/json" \
#      -d '{"name": "Cybersecurity", "parent_id": null}'


# for crate question 

POST http://localhost:3000/questions
Content-Type: application/json

{
  "question_text": "In a relational database, what does SQL stand for for testing data?",
  "assessment_id": 7, 
    "points": 1,
  "options": [
    { "option_text": "Structured Question Language", "is_correct": false },
    { "option_text": "Simple Query Language", "is_correct": true },
    { "option_text": "Structured Query Language", "is_correct": true },
    { "option_text": "Sequential Query Logi", "is_correct": false }
  ],
  "is_multiple_choice": true
}

# # submit answer test

# POST http://localhost:3000/questions/submit-answer
# Content-Type: application/json

# {
#   "question_id": 50,
#   "option_ids": [150,151],  
#   "user_id": 2
# }

# POST http://localhost:3000/questions/submit-answer
# Content-Type: application/json

# {
#   "question_id": 49,
#   "option_ids": [147], 
#   "user_id": 2
# }
